# Generated by Django 5.0 on 2024-01-05 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avto_name', models.CharField(max_length=255)),
                ('motor', models.CharField(max_length=10)),
                ('compani', models.CharField(max_length=255)),
                ('mony', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AvtoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('avto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.avto')),
            ],
        ),
    ]
